SECTION TEXT
INPUT OLD_DATA + 1;teste
LOAD OLD_DATA ; teste1, linha em branco abaixo eh proposital

;teste2 com comentario em linha unica
L1:
DIV DOIS
STORE  NEW_DATA
;ADD -0x15
;SUB 03
MULT DOIS
STORE TMP_DATA
LOAD OLD_DATA
SUB TMP_DATA
STORE TMP_DATA
OUTPUT TMP_DATA
COPY NEW_DATA, OLD_DATA
LOAD OLD_DATA
JMPP L1
STOP
SECTION DATA
DOIS: CONST 2
OLD_DATA: SPACE
NEW_DATA: SPACE
TMP_DATA: SPACE